name: srmdot
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  simple_animations: ^1.3.3
  flutter_screenutil: ^0.4.2
  page_transition: ^1.1.4
  flare_flutter: ^2.0.3
  flutter_bloc: ^2.1.1
  dropdownfield: ^1.0.3
  qr_code_scanner: ^0.0.13
  circulardropdownmenu: ^1.0.1
  http: ^0.12.1
  mysql1: ^0.17.1
  table_sticky_headers: ^1.1.2
  flutter_svg:
  syncfusion_flutter_charts: ^18.1.56
  fl_chart: ^0.10.0
  amazon_cognito_identity_dart_2: ^0.1.14
  rflutter_alert: ^1.0.3
  flutter_staggered_grid_view: ^0.3.0
  smart_grid_view: ^0.2.1
  bubble_bottom_bar: ^1.2.0
  google_maps_flutter:
  url_launcher: ^5.5.0
  back_button_interceptor: ^4.3.0




















dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/screenshots/
    - assets/images/
    - assets/flare/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: LexendGiga
      fonts:
       - asset: assets/fonts/LexendGiga-Regular.ttf
    - family: BalsamiqSans
      fonts:
       - asset: assets/fonts/BalsamiqSans-Regular.ttf
    - family: Gotu
      fonts:
       - asset: assets/fonts/Gotu-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
